### ISSUE TITLE
not work for me

### ISSUE THREAD

**Issue by abbasalim** [Tweener/alarmee#3]
hi,
Although it says that a notification is supposed to be sent, nothing is sent!
persmissions is enabled:
android:
<img width="1081" alt="Screenshot 2024-11-26 at 20 21 38" src="https://github.com/user-attachments/assets/f1f4038e-5fdd-45e4-98bf-97d59a90439a">
<img width="322" alt="Screenshot 2024-11-26 at 20 23 37" src="https://github.com/user-attachments/assets/c16535cf-1c78-42af-8402-917b0454ea43">

ios:
<img width="890" alt="Screenshot 2024-11-26 at 20 33 56" src="https://github.com/user-attachments/assets/298629f9-ad95-4478-ad6f-8fc7e6a9dcb7">

**Comment by Tweener** [comment]
Hi @abbasalim ,
Do you have the notifications permission granted on both iOS and Android?

**Comment by abbasalim** [comment]
Yes ![image](https://github.com/user-attachments/assets/9b9dadce-4a67-44c2-aeb2-addaea82b785)

**Comment by Tweener** [comment]
Can you show me the part of the code where you create the Alarmee, please? (`alarmeeScheduler.schedule(...)`)

**Comment by abbasalim** [comment]
```

@Composable
private fun SendWeeklyNotif() {
    ///todo now show notif
    println("SendWeeklyNotif called")
    createAlarmeePlatformConfiguration()?.let { alarmConfig ->
        if (alarmConfig is AlarmeePlatformConfiguration) {
            val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
            val time = LocalTime(hour = now.hour, minute = now.minute, second = now.second+5)
            val date = LocalDateTime(date = now.date, time = time)
            //
            val alarmeeScheduler: AlarmeeScheduler =
                rememberAlarmeeScheduler(platformConfiguration = alarmConfig)
            alarmeeScheduler.schedule(
                alarmee = Alarmee(
                    uuid = now.toString(),
                    notificationTitle = "🔁 Congratulations! You've schedule a repeating Alarmee!",
                    notificationBody = "This is the notification that will be displayed every.",
                    scheduledDateTime = date,
//                    repeatInterval = RepeatInterval.WEEKLY,
                    androidNotificationConfiguration = AndroidNotificationConfiguration(
                        priority = AndroidNotificationPriority.DEFAULT,
                        notificationChannelId = "suggesstion_channel2",
                    ),
                )
            )

        }
    }
}

```

I call this func in App()

**Comment by Tweener** [comment]
Are you sure you created a channel with ID `suggesstion_channel2`? (From your screenshot, it looks like you copy pasted the code from the example in the README)

**Comment by abbasalim** [comment]
Thanks, now work on android, but doesn't work on iOS yet

**Comment by Tweener** [comment]
First of all, on iOS, ensure your app is in the background to see the notification. If your app is in the foreground, the system delivers the notification to your app for handling instead. See [documentation](https://developer.apple.com/documentation/usernotifications/scheduling-a-notification-locally-from-your-app#overview).

Secondly, you're setting an alarm based on seconds (`second = now.second+5`), but the library currently does not handle granularity for seconds. To make it work, remove the `second = ...` parameter and set it to the next minute (e.g., `minute = now.minute + 1`).
I will update the logic in the library to support seconds in the future.

Let me know if this helps.

**Comment by abbasalim** [comment]
Thanks, Now everything works fine, but I have two problems
1- when clicked on notification in android, nothing happened, app not run!
2- I can't run desktop version of my app, please give a solution for this, Even if not work notification at least run app
لااقل

**Comment by Tweener** [comment]
Glad to know it finally works!

About your issues:
1. On Android, in your `AndroidManifest.xml` file, make sure you [declared an activity](https://developer.android.com/reference/android/content/pm/PackageManager#getLaunchIntentForPackage(java.lang.String)) with a category `android.intent.category.INFO` or `android.intent.category.LAUNCHER` as intent-filter. Otherwise the system does not know which activity to launch from the notification.
2. I can check if I can easily add the desktop target, but without proper implementation for now. Which means the library will be available on desktop but you won't be able to schedule alarms.

**Comment by abbasalim** [comment]
Thanks, this is great but give me error for jvm version

<img width="476" alt="Screenshot 2024-11-29 at 21 49 02" src="https://github.com/user-attachments/assets/8baf6068-822c-4c81-8ba2-d7785ed5ec09">
<img width="1172" alt="Screenshot 2024-11-29 at 21 48 58" src="https://github.com/user-attachments/assets/d90606ff-217f-4773-9c40-2d329a451118">

**Comment by Tweener** [comment]
It looks like a configuration error on your side. Alarmee is published on Maven Central, not on Jitpack. Check your dependency an repository configuration to make sure it's looking on Maven Central.

**Comment by abbasalim** [comment]
![Uploading Screenshot 2024-12-07 at 17.02.32.png…]()

**Comment by abbasalim** [comment]
<img width="802" alt="Screenshot 2024-12-07 at 17 02 32" src="https://github.com/user-attachments/assets/32929189-3d9f-4340-8a04-80f28ca6dad9">

**Comment by Tweener** [comment]
Yes, that's what I'm saying and from your screenshot, Gradle seems to be looking in the wrong places.
**Alarmee** is not published on Jitpack so you probably have a misconfiguration in your setup. In your `settings.gradle.kts`, did you add `mavenCentral()` in the `dependencyResolutionManagement` block?

**Comment by abbasalim** [comment]
<img width="552" alt="Screenshot 2024-12-08 at 09 16 19" src="https://github.com/user-attachments/assets/5dc3cb78-9ef6-4e80-a247-00cae992a8f0">

بله
<img width="683" alt="Screenshot 2024-12-08 at 09 17 22" src="https://github.com/user-attachments/assets/e138187f-1ab8-4a20-b748-ac36efc698f9">

yes

**Comment by Tweener** [comment]
I figured out what was happening. Can you try again, please?

**Comment by abbasalim** [comment]
Yes, everything is working well now.

**Comment by Tweener** [comment]
Perfect, glad it's working now.
